# If you want to override a RoboDrupal8 Configurations.

#composer:
#    bin: /var/www/html/test-rd8/vendor/bin
#    extra: ''

#database:
#    name: ''
#    host: ''
#    port: '3306'
#    username: ''
#    password: ''

#docroot: /var/www/html/test-rd8/docroot

#drupal:
#    site: { machine_name: default, profile: standard, name: Drupal, mail: info@local.local }
#    account: { username: admin, mail: admin@local.local, password: admin }
#    locale: en
#    local_settings_file: ''
#    settings_file: ''
#    url: 'http://default.rd8'

#drush:
#    bin: ./vendor/bin/drush
#    dir: /docroot
#    uri: default
#    sanitaze: true
#    alias: null

#git:
#    hooks: { pre-commit: /var/www/html/robo-drupal8/scripts/git-hooks, commit-msg: /var/www/html/robo-drupal8/scripts/git-hooks }
#    commit-msg: { pattern: '/(^RD8-[0-9]+(: )[^ ].{15,}\.)|(Merge branch (.)+)/' }

#options:
#    decorated: true
#    interactive: true
#    progress-delay: 2
#    simulate: false
#    help: false
#    quiet: false
#    verbose: false
#    version: false
#    ansi: false
#    no-ansi: false
#    no-interaction: false
#    'yes': false
#    define: {  }
#    site: default

#phpcs:
#    bin: ''
#    standard: 'Drupal,DrupalPractice'

#phpunit:
#    bin: ''

#project:
#    root: /var/www/html/test-rd8
#    machine_name: rd8
#    prefix: RD8
#    human_name: 'RoboDrupal 8 Example Project'

#rd8:
#    root: /var/www/html/robo-drupal8
#    version: 2.x

#site: default
