################################################################################
### Project configuration.
project:
  machine_name: 'rd8-project'
  # Used for enforcing correct git commit msg syntax.
  prefix: 'RD8'
  human_name: 'RooDrupal8 Test Project'

# Composer.
bin.path: vendor/bin
composer:
  bin: ${repo.root}/${bin.path}
  extra: ''

# File and Directory locations.
docroot: ${repo.root}/docroot

# Git.
git:
  # The value of a hook should be the file path to a directory containing an
  # executable file named after the hook.
  # Changing a hook value to 'false' will disable it.
  hooks:
    pre-commit: ${blt.root}/scripts/git-hooks
    commit-msg: ${blt.root}/scripts/git-hooks
  commit-msg:
    # Commit messages must conform to this pattern.
    pattern: "/(^${project.prefix}-[0-9]+(: )[^ ].{15,}\\.)|(Merge branch (.)+)/"

# PHPCs.
phpcs:
  standard: Drupal,DrupalPractice

# PhpUnit.
phpunit:
  - path: ${repo.root}/tests/phpunit
    class: 'ExampleTest'
    file: 'ExampleTest.php'
    config: null
  # Customization for one or more custom phpunit test locations
  # and if the core (or custom) config file should be included as a -c parameter.
  # - path: '${docroot}/modules/custom/<your_module'
  #   config: '${docroot}/core/phpunit.xml.dist'
  # - path: '${docroot}/core'
  #   config: '${docroot}/core/phpunit.xml.dist'

# Drush.
drush:
  bin: ${composer.bin}/drush
  dir: ${docroot}
  sanitize: true

# TODO: DrupalConsole configuration?

################################################################################
### Drupal Configuration.
drupal:
  site_name: default
  account:
    mail: admin@localhost
    username: admin
    password: admin
  locale: en
  local_settings_file: ${docroot}/sites/${site}/settings/local.settings.php
  settings_file: ${docroot}/sites/${site}/settings.php
  db:
    database: drupal
    username: drupal
    password: drupal
    host: localhost
    port: 3306
  url: http://${drupal.site_name}.${project.machine_name}